#ifndef __MalpkaMyFrame__
#define __MalpkaMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "Malpka.h"

//// end generated include

#include <wx/dcclient.h>
#include <wx/colordlg.h>
#include <wx/dc.h>
#include <wx/bitmap.h>
#include <wx/graphics.h>

/** Implementing MyFrame */
class MalpkaMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void m_panelOnPaint( wxPaintEvent& event );
		void m_panelOnSize( wxSizeEvent& event );
		void m_checkBox_bananaOnCheckBox( wxCommandEvent& event );
		void m_scrollBarOnScroll( wxScrollEvent& event );
		void m_button_colorOnButtonClick( wxCommandEvent& event );
		void m_textCtrlOnText( wxCommandEvent& event );
		void m_choice_figuraOnChoice( wxCommandEvent& event );
	public:
		/** Constructor */
		MalpkaMyFrame( wxWindow* parent );
	//// end generated class members

	wxColour m_starColour;
	wxBitmap m_bananaBitmap;
	bool m_hasBanana = false;
	double m_bananaAngle = 0;

	void DrawMonkey(wxDC& dc);
	void DrawGraphicSymbol(wxDC& dc, int x, int y, int size);
	void DrawStar(wxDC& dc, int x, int y, int size);
	void DrawSun(wxDC& dc, int x, int y, int size);
	void DrawMoon(wxDC& dc, int x, int y, int size);
	void DrawTextElements(wxDC& dc);

















};

#endif // __MalpkaMyFrame__
